import type { ProductCategory } from '@/types/product';

export const categories: ProductCategory[] = [
  // ─── Level 1: Two top-level branches ──────────────────────────────────────
  {
    slug: 'raw-materials',
    name: { en: 'Chemical Raw Materials', zh: '化工原料' },
    summary: {
      en: 'Polyolefin resins for film, packaging, injection moulding, and engineering applications.',
      zh: '面向薄膜、包装、注塑与工程应用的聚烯烃树脂。',
    },
    image: 'category-raw-materials',
    sortOrder: 1,
    enabled: true,
    path: ['raw-materials'],
    parentSlug: null,
    level: 1,
    isLeaf: false,
  },
  {
    slug: 'manufactured',
    name: { en: 'Manufactured Goods', zh: '制品' },
    summary: {
      en: 'Finished consumer and household goods produced from polyolefin resins.',
      zh: '由聚烯烃树脂加工而成的消费与家居制品。',
    },
    image: 'category-manufactured',
    sortOrder: 2,
    enabled: true,
    path: ['manufactured'],
    parentSlug: null,
    level: 1,
    isLeaf: false,
  },

  // ─── Level 2: PE / PP under raw-materials ─────────────────────────────────
  {
    slug: 'pe',
    name: { en: 'Polyethylene (PE)', zh: '聚乙烯 (PE)' },
    summary: {
      en: 'Comprehensive PE portfolio including LDPE, HDPE, LLDPE, and metallocene LLDPE grades.',
      zh: '完整的聚乙烯产品线，涵盖 LDPE、HDPE、LLDPE 与茂金属 LLDPE。',
    },
    image: 'category-pe',
    sortOrder: 1,
    enabled: true,
    path: ['raw-materials', 'pe'],
    parentSlug: 'raw-materials',
    level: 2,
    isLeaf: false,
  },
  {
    slug: 'pp',
    name: { en: 'Polypropylene (PP)', zh: '聚丙烯 (PP)' },
    summary: {
      en: 'Full PP portfolio: homopolymer, impact copolymer, random copolymer, terpolymer, and modified grades.',
      zh: '完整的聚丙烯产品线：均聚、嵌段共聚、无规共聚、三元共聚与改性专用牌号。',
    },
    image: 'category-pp',
    sortOrder: 2,
    enabled: true,
    path: ['raw-materials', 'pp'],
    parentSlug: 'raw-materials',
    level: 2,
    isLeaf: false,
  },

  // ─── Level 3: PE sub-branches ─────────────────────────────────────────────
  {
    slug: 'ldpe',
    name: { en: 'Low-Density Polyethylene (LDPE)', zh: '低密度聚乙烯 (LDPE)' },
    summary: {
      en: 'Highly branched PE with excellent clarity and flexibility for film, coatings, and squeeze containers.',
      zh: '高支化聚乙烯，透明度与柔韧性优异，适用于薄膜、涂层与挤出容器。',
    },
    image: 'category-pe',
    sortOrder: 1,
    enabled: true,
    path: ['raw-materials', 'pe', 'ldpe'],
    parentSlug: 'pe',
    level: 3,
    isLeaf: true,
  },
  {
    slug: 'hdpe',
    name: { en: 'High-Density Polyethylene (HDPE)', zh: '高密度聚乙烯 (HDPE)' },
    summary: {
      en: 'Linear PE with high stiffness, tensile strength, and chemical resistance for blow moulding, pipe, and rigid containers.',
      zh: '线性聚乙烯，刚性、拉伸强度与耐化学性优良，适用于吹塑、管材与硬质容器。',
    },
    image: 'category-pe',
    sortOrder: 2,
    enabled: true,
    path: ['raw-materials', 'pe', 'hdpe'],
    parentSlug: 'pe',
    level: 3,
    isLeaf: true,
  },
  {
    slug: 'lldpe',
    name: { en: 'Linear Low-Density Polyethylene (LLDPE)', zh: '线性低密度聚乙烯 (LLDPE)' },
    summary: {
      en: 'Linear short-branched PE delivering superior toughness and puncture resistance — available with butene (C4) or hexene (C6) comonomers.',
      zh: '线性短支化聚乙烯，韧性与抗穿刺性突出，按共聚单体分为丁烯 (C4) 与己烯 (C6) 两类。',
    },
    image: 'category-pe',
    sortOrder: 3,
    enabled: true,
    path: ['raw-materials', 'pe', 'lldpe'],
    parentSlug: 'pe',
    level: 3,
    isLeaf: false,
  },
  {
    slug: 'mlldpe',
    name: { en: 'Metallocene LLDPE (mLLDPE)', zh: '茂金属线性低密度聚乙烯 (MLLDPE)' },
    summary: {
      en: 'Metallocene-catalysed LLDPE with narrow molecular-weight distribution — premium toughness and optical performance.',
      zh: '采用茂金属催化的 LLDPE，分子量分布窄，韧性与光学性能更优。',
    },
    image: 'category-pe',
    sortOrder: 4,
    enabled: true,
    path: ['raw-materials', 'pe', 'mlldpe'],
    parentSlug: 'pe',
    level: 3,
    isLeaf: false,
  },

  // ─── Level 4: LLDPE comonomer variants ────────────────────────────────────
  {
    slug: 'lldpe-c4',
    name: { en: 'C4 (Butene-based LLDPE)', zh: 'C4（丁烯共聚 LLDPE）' },
    summary: {
      en: 'Standard butene-comonomer LLDPE for general-purpose film and packaging applications.',
      zh: '丁烯共聚 LLDPE，标准通用牌号，适用于薄膜与包装。',
    },
    image: 'category-pe',
    sortOrder: 1,
    enabled: true,
    path: ['raw-materials', 'pe', 'lldpe', 'lldpe-c4'],
    parentSlug: 'lldpe',
    level: 4,
    isLeaf: true,
  },
  {
    slug: 'lldpe-c6',
    name: { en: 'C6 (Hexene-based LLDPE)', zh: 'C6（己烯共聚 LLDPE）' },
    summary: {
      en: 'Hexene-comonomer LLDPE — improved tear resistance and puncture strength versus C4 grades.',
      zh: '己烯共聚 LLDPE，相比 C4 牌号有更优异的抗撕裂与抗穿刺性能。',
    },
    image: 'category-pe',
    sortOrder: 2,
    enabled: true,
    path: ['raw-materials', 'pe', 'lldpe', 'lldpe-c6'],
    parentSlug: 'lldpe',
    level: 4,
    isLeaf: true,
  },

  // ─── Level 4: mLLDPE comonomer variants ───────────────────────────────────
  {
    slug: 'mlldpe-c6',
    name: { en: 'C6 (Hexene-based mLLDPE)', zh: 'C6（己烯共聚 MLLDPE）' },
    summary: {
      en: 'Metallocene C6 LLDPE — high-performance film resin with outstanding toughness and clarity.',
      zh: '茂金属 C6 LLDPE 高性能薄膜树脂，韧性与透明度俱佳。',
    },
    image: 'category-pe',
    sortOrder: 1,
    enabled: true,
    path: ['raw-materials', 'pe', 'mlldpe', 'mlldpe-c6'],
    parentSlug: 'mlldpe',
    level: 4,
    isLeaf: true,
  },
  {
    slug: 'mlldpe-c8',
    name: { en: 'C8 (Octene-based mLLDPE)', zh: 'C8（辛烯共聚 MLLDPE）' },
    summary: {
      en: 'Octene-comonomer metallocene LLDPE — reserved category for future imported grades.',
      zh: '辛烯共聚茂金属 LLDPE — 该窗口为后续引入进口牌号预留。',
    },
    image: 'category-pe',
    sortOrder: 2,
    enabled: true,
    path: ['raw-materials', 'pe', 'mlldpe', 'mlldpe-c8'],
    parentSlug: 'mlldpe',
    level: 4,
    isLeaf: true,
  },

  // ─── Level 3: PP sub-branches ─────────────────────────────────────────────
  {
    slug: 'pp-homo',
    name: { en: 'Homopolymer PP', zh: '均聚 PP' },
    summary: {
      en: 'Single-monomer PP with high stiffness, hardness, and heat resistance. Brittle at low temperatures.',
      zh: '单一单体聚合的均聚 PP，刚性、硬度与耐热性突出，低温下偏脆。',
    },
    image: 'category-pp',
    sortOrder: 1,
    enabled: true,
    path: ['raw-materials', 'pp', 'pp-homo'],
    parentSlug: 'pp',
    level: 3,
    isLeaf: true,
  },
  {
    slug: 'pp-impact',
    name: { en: 'Impact Copolymer PP', zh: '嵌段共聚 PP' },
    summary: {
      en: 'PP/ethylene impact copolymer offering balanced low-temperature impact strength and stiffness — ideal for large injection-moulded parts.',
      zh: '丙烯-乙烯嵌段共聚 PP，兼顾低温抗冲击与刚性，适合注塑大件。',
    },
    image: 'category-pp',
    sortOrder: 2,
    enabled: true,
    path: ['raw-materials', 'pp', 'pp-impact'],
    parentSlug: 'pp',
    level: 3,
    isLeaf: true,
  },
  {
    slug: 'pp-random',
    name: { en: 'Random Copolymer PP', zh: '无规共聚 PP' },
    summary: {
      en: 'PP randomly copolymerised with ethylene for high transparency and gloss — used in clear injection moulded and blow-moulded products.',
      zh: '丙烯与少量乙烯无规共聚，透明度与光泽优良，适用于透明吹塑与挤出制品。',
    },
    image: 'category-pp',
    sortOrder: 3,
    enabled: true,
    path: ['raw-materials', 'pp', 'pp-random'],
    parentSlug: 'pp',
    level: 3,
    isLeaf: true,
  },
  {
    slug: 'pp-terpoly',
    name: { en: 'Terpolymer PP', zh: '三元共聚 PP' },
    summary: {
      en: 'Propylene-ethylene-butene terpolymer PP — high transparency, low haze, and improved low-temperature toughness for food packaging films.',
      zh: '丙烯-乙烯-丁烯三元共聚 PP，高透明、低雾度、低温韧性提升，专用于食品包装膜。',
    },
    image: 'category-pp',
    sortOrder: 4,
    enabled: true,
    path: ['raw-materials', 'pp', 'pp-terpoly'],
    parentSlug: 'pp',
    level: 3,
    isLeaf: true,
  },
  {
    slug: 'pp-hico',
    name: { en: 'High-Impact Copolymer PP', zh: '高抗冲共聚 PP' },
    summary: {
      en: 'Higher ethylene-content copolymer PP with ultra-low temperature impact strength — used in automotive parts and durable household goods.',
      zh: '乙烯含量更高的共聚 PP，超低温冲击强度突出，应用于汽车配件与耐用家居制品。',
    },
    image: 'category-pp',
    sortOrder: 5,
    enabled: true,
    path: ['raw-materials', 'pp', 'pp-hico'],
    parentSlug: 'pp',
    level: 3,
    isLeaf: true,
  },
  {
    slug: 'pp-modified',
    name: { en: 'Modified PP', zh: '改性专用 PP' },
    summary: {
      en: 'Application-specific modified PP — glass-fibre reinforced, flame-retardant, filled, or weather-resistant grades.',
      zh: '面向特定应用的改性 PP — 含玻纤增强、阻燃、填充与耐候等专用牌号。',
    },
    image: 'category-pp',
    sortOrder: 6,
    enabled: true,
    path: ['raw-materials', 'pp', 'pp-modified'],
    parentSlug: 'pp',
    level: 3,
    isLeaf: true,
  },

  // ─── Level 2: Manufactured goods sub-branches ─────────────────────────────
  {
    slug: 'kitchen',
    name: { en: 'Kitchen & Household', zh: '厨房与生活用品' },
    summary: {
      en: 'Polymer-based household goods including cling film, basins, and other kitchen essentials.',
      zh: '聚合物基家居用品，包括保鲜膜、脸盆等厨房日用品。',
    },
    image: 'category-kitchen',
    sortOrder: 1,
    enabled: true,
    path: ['manufactured', 'kitchen'],
    parentSlug: 'manufactured',
    level: 2,
    isLeaf: false,
  },

  // ─── Level 3: Manufactured leaf categories ────────────────────────────────
  {
    slug: 'cling-film',
    name: { en: 'Cling Film', zh: '保鲜膜' },
    summary: {
      en: 'Thin, stretchable PE film for food preservation and household wrapping.',
      zh: '用于食品保鲜与家用包裹的薄型可拉伸聚乙烯膜。',
    },
    image: 'category-kitchen',
    sortOrder: 1,
    enabled: true,
    path: ['manufactured', 'kitchen', 'cling-film'],
    parentSlug: 'kitchen',
    level: 3,
    isLeaf: true,
  },
  {
    slug: 'wash-basin',
    name: { en: 'Wash Basin', zh: '脸盆' },
    summary: {
      en: 'Injection-moulded PP wash basins for everyday household use.',
      zh: '注塑成型的聚丙烯脸盆，适用于日常家居生活。',
    },
    image: 'category-kitchen',
    sortOrder: 2,
    enabled: true,
    path: ['manufactured', 'kitchen', 'wash-basin'],
    parentSlug: 'kitchen',
    level: 3,
    isLeaf: true,
  },
];
