import type { Product } from '@/types/product';

export const products: Product[] = [
  {
    slug: 'caustic-soda-flakes-99',
    name: { en: 'Caustic Soda Flakes 99%', zh: '片碱 99%' },
    category: 'industrial-chemicals',
    casNo: '1310-73-2',
    summary: {
      en: 'High-purity sodium hydroxide in flake form for industrial use.',
      zh: '工业级高纯度片状氢氧化钠。',
    },
    overview: {
      en: 'Caustic soda flakes (sodium hydroxide, NaOH) at 99% min purity. Widely used in pulp & paper, textile processing, soap manufacturing, and water treatment. Strongly hygroscopic — store in dry, sealed containers away from acids.',
      zh: '99% 最小纯度的片状氢氧化钠（NaOH）。广泛用于制浆造纸、纺织、肥皂制造与水处理。强吸湿性，应存放于干燥密封容器中并远离酸性物质。',
    },
    grade: { en: 'Industrial', zh: '工业级' },
    purity: '99% min',
    packaging: [
      { en: '25kg PP woven bag', zh: '25 公斤 PP 编织袋' },
      { en: '1MT bulk bag (jumbo)', zh: '1 吨吨袋（吨包）' },
    ],
    applications: [
      { en: 'Pulp & paper manufacturing', zh: '制浆造纸' },
      { en: 'Textile processing', zh: '纺织加工' },
      { en: 'Soap & detergent manufacturing', zh: '肥皂与洗涤剂制造' },
      { en: 'Water treatment (pH adjustment)', zh: '水处理（pH 调节）' },
    ],
    documents: ['COA', 'TDS', 'SDS'],
    specs: [
      { label: { en: 'Purity (NaOH)', zh: '纯度 (NaOH)' }, value: { en: '99% min', zh: '≥ 99%' } },
      { label: { en: 'Appearance', zh: '外观' }, value: { en: 'White flakes', zh: '白色片状' } },
      { label: { en: 'Bulk density', zh: '堆积密度' }, value: { en: '~ 0.9 g/cm³', zh: '约 0.9 g/cm³' } },
      { label: { en: 'Solubility (water, 20°C)', zh: '水溶性 (20°C)' }, value: { en: '1110 g/L', zh: '1110 g/L' } },
      { label: { en: 'Storage', zh: '储存' }, value: { en: 'Dry, sealed, away from acids', zh: '干燥密封，远离酸性物质' } },
      { label: { en: 'Shelf life', zh: '保质期' }, value: { en: '24 months in sealed packaging', zh: '密封包装下 24 个月' } },
    ],
    relatedProductSlugs: ['hydrochloric-acid-31', 'sodium-hypochlorite', 'citric-acid'],
    image: 'product-default',
    heroImage: 'page-hero',
    featured: true,
    published: true,
    sortOrder: 1,
    seoTitle: {
      en: 'Caustic Soda Flakes 99% (NaOH, CAS 1310-73-2) — AOWATT',
      zh: '片碱 99%（氢氧化钠，CAS 1310-73-2）— AOWATT',
    },
    seoDescription: {
      en: 'Industrial caustic soda flakes 99% min purity, 25kg PP bag or 1MT bulk packaging. Contact AOWATT Global Materials for export quotation.',
      zh: '工业级片碱，99% 最小纯度，25 公斤袋或 1 吨吨袋包装。如需出口报价，请联系 AOWATT Global Materials。',
    },
  },
  {
    slug: 'hydrochloric-acid-31',
    name: { en: 'Hydrochloric Acid 31%', zh: '盐酸 31%' },
    category: 'industrial-chemicals',
    casNo: '7647-01-0',
    summary: {
      en: 'Industrial-grade hydrochloric acid solution at 31% concentration.',
      zh: '31% 浓度的工业级盐酸溶液。',
    },
    overview: {
      en: 'Hydrochloric acid (HCl) at 31% ±1% concentration. Standard reagent for steel pickling, water treatment pH adjustment, and food-grade processing (where grade-appropriate). Highly corrosive — handle with chemical-resistant equipment.',
      zh: '31% ±1% 浓度的盐酸（HCl）。是钢铁酸洗、水处理 pH 调节与食品加工（在相应等级下）的标准试剂。强腐蚀性，须使用耐化学品设备操作。',
    },
    grade: { en: 'Industrial', zh: '工业级' },
    purity: '31% ±1%',
    packaging: [
      { en: '200kg HDPE drum', zh: '200 公斤 HDPE 桶' },
      { en: '1100kg IBC tank', zh: '1100 公斤 IBC 吨桶' },
    ],
    applications: [
      { en: 'Steel pickling & metal cleaning', zh: '钢铁酸洗与金属清洗' },
      { en: 'Water treatment (pH adjustment)', zh: '水处理（pH 调节）' },
      { en: 'Chemical synthesis', zh: '化学合成' },
      { en: 'Food processing (grade-dependent)', zh: '食品加工（依等级）' },
    ],
    documents: ['COA', 'TDS', 'SDS'],
    specs: [
      { label: { en: 'Concentration (HCl)', zh: '浓度 (HCl)' }, value: { en: '31% ±1%', zh: '31% ±1%' } },
      { label: { en: 'Appearance', zh: '外观' }, value: { en: 'Clear yellowish liquid', zh: '透明微黄液体' } },
      { label: { en: 'Density (20°C)', zh: '密度 (20°C)' }, value: { en: '~ 1.16 g/cm³', zh: '约 1.16 g/cm³' } },
      { label: { en: 'Free chlorine', zh: '游离氯' }, value: { en: '< 30 ppm', zh: '< 30 ppm' } },
      { label: { en: 'Iron (Fe)', zh: '铁 (Fe)' }, value: { en: '< 5 ppm', zh: '< 5 ppm' } },
      { label: { en: 'Storage', zh: '储存' }, value: { en: 'Cool, ventilated, acid-resistant container', zh: '阴凉通风，耐酸容器储存' } },
    ],
    relatedProductSlugs: ['caustic-soda-flakes-99', 'sodium-hypochlorite', 'citric-acid'],
    image: 'product-default',
    heroImage: 'page-hero',
    featured: true,
    published: true,
    sortOrder: 2,
    seoTitle: {
      en: 'Hydrochloric Acid 31% (HCl, CAS 7647-01-0) — AOWATT',
      zh: '盐酸 31%（HCl，CAS 7647-01-0）— AOWATT',
    },
    seoDescription: {
      en: 'Industrial hydrochloric acid 31% in 200kg drum or 1100kg IBC. Contact AOWATT Global Materials for export quotation.',
      zh: '工业级盐酸 31%，200 公斤桶或 1100 公斤 IBC 包装。如需出口报价，请联系 AOWATT Global Materials。',
    },
  },
  {
    slug: 'sodium-hypochlorite',
    name: { en: 'Sodium Hypochlorite', zh: '次氯酸钠' },
    category: 'water-treatment',
    casNo: '7681-52-9',
    summary: {
      en: '[PLACEHOLDER] Industrial bleach for disinfection and water treatment.',
      zh: '[PLACEHOLDER] 用于消毒与水处理的工业漂白剂。',
    },
    overview: { en: '[PLACEHOLDER] Overview pending product data confirmation.', zh: '[PLACEHOLDER] 概述待产品数据确认。' },
    packaging: [{ en: '[PLACEHOLDER] Packaging TBC', zh: '[PLACEHOLDER] 包装待定' }],
    applications: [{ en: '[PLACEHOLDER] Applications TBC', zh: '[PLACEHOLDER] 应用待定' }],
    documents: ['COA', 'SDS'],
    specs: [
      { label: { en: '[PLACEHOLDER] Spec label', zh: '[PLACEHOLDER] 规格标签' }, value: { en: '[PLACEHOLDER] value', zh: '[PLACEHOLDER] 值' } },
    ],
    relatedProductSlugs: ['caustic-soda-flakes-99', 'hydrochloric-acid-31', 'citric-acid'],
    image: 'product-default',
    featured: true,
    published: false,  // V0.1: Hide until product data confirmed
    placeholder: true,
    sortOrder: 3,
  },
  {
    slug: 'industrial-solvent-blend',
    name: { en: 'Industrial Solvent Blend', zh: '工业溶剂混合物' },
    category: 'solvents',
    summary: { en: '[PLACEHOLDER] Solvent mixture for industrial cleaning and formulation.', zh: '[PLACEHOLDER] 工业清洗与配方用溶剂混合物。' },
    overview: { en: '[PLACEHOLDER] Overview pending.', zh: '[PLACEHOLDER] 概述待定。' },
    packaging: [{ en: '[PLACEHOLDER] Packaging TBC', zh: '[PLACEHOLDER] 包装待定' }],
    applications: [{ en: '[PLACEHOLDER] Applications TBC', zh: '[PLACEHOLDER] 应用待定' }],
    documents: ['TDS', 'SDS'],
    specs: [
      { label: { en: '[PLACEHOLDER] Spec label', zh: '[PLACEHOLDER] 规格标签' }, value: { en: '[PLACEHOLDER] value', zh: '[PLACEHOLDER] 值' } },
    ],
    relatedProductSlugs: ['caustic-soda-flakes-99', 'hydrochloric-acid-31', 'citric-acid'],
    image: 'product-default',
    featured: true,
    published: false,  // V0.1: Hide until product data confirmed
    placeholder: true,
    sortOrder: 4,
  },
  {
    slug: 'citric-acid',
    name: { en: 'Citric Acid', zh: '柠檬酸' },
    category: 'specialty-chemicals',
    casNo: '77-92-9',
    summary: { en: '[PLACEHOLDER] Specialty acid for food, beverage, and industrial use.', zh: '[PLACEHOLDER] 用于食品、饮料与工业的特种酸。' },
    overview: { en: '[PLACEHOLDER] Overview pending.', zh: '[PLACEHOLDER] 概述待定。' },
    packaging: [{ en: '[PLACEHOLDER] Packaging TBC', zh: '[PLACEHOLDER] 包装待定' }],
    applications: [{ en: '[PLACEHOLDER] Applications TBC', zh: '[PLACEHOLDER] 应用待定' }],
    documents: ['COA', 'TDS'],
    specs: [
      { label: { en: '[PLACEHOLDER] Spec label', zh: '[PLACEHOLDER] 规格标签' }, value: { en: '[PLACEHOLDER] value', zh: '[PLACEHOLDER] 值' } },
    ],
    relatedProductSlugs: ['caustic-soda-flakes-99', 'hydrochloric-acid-31', 'sodium-hypochlorite'],
    image: 'product-default',
    featured: true,
    published: false,  // V0.1: Hide until product data confirmed
    placeholder: true,
    sortOrder: 5,
  },
  {
    slug: 'mining-collector-reagent',
    name: { en: 'Mining Collector Reagent', zh: '矿用捕收剂' },
    category: 'mining-chemicals',
    summary: { en: '[PLACEHOLDER] Flotation collector for mineral processing.', zh: '[PLACEHOLDER] 矿物加工浮选捕收剂。' },
    overview: { en: '[PLACEHOLDER] Overview pending.', zh: '[PLACEHOLDER] 概述待定。' },
    packaging: [{ en: '[PLACEHOLDER] Packaging TBC', zh: '[PLACEHOLDER] 包装待定' }],
    applications: [{ en: '[PLACEHOLDER] Applications TBC', zh: '[PLACEHOLDER] 应用待定' }],
    documents: ['SDS'],
    specs: [
      { label: { en: '[PLACEHOLDER] Spec label', zh: '[PLACEHOLDER] 规格标签' }, value: { en: '[PLACEHOLDER] value', zh: '[PLACEHOLDER] 值' } },
    ],
    relatedProductSlugs: ['caustic-soda-flakes-99', 'hydrochloric-acid-31', 'sodium-hypochlorite'],
    image: 'product-default',
    featured: true,
    published: false,  // V0.1: Hide until product data confirmed
    placeholder: true,
    sortOrder: 6,
  },
];
